name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: siliconacr9.azurecr.io
        username: ${{ secrets.AZURE_CR_USERNAME }}
        password: ${{ secrets.AZURE_CR_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.AZURE_CR_USERNAME }}/myapp:${{ github.sha }}
        labels: type=image

    
